# Generated by Django 5.2 on 2025-04-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='data_vencimento',
            new_name='dataVencimento',
        ),
    ]
